// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// stateT
NumericMatrix stateT(int origin, IntegerVector newstates, NumericVector cumuprobs, NumericMatrix sMatrix);
RcppExport SEXP ibmcraftr_stateT(SEXP originSEXP, SEXP newstatesSEXP, SEXP cumuprobsSEXP, SEXP sMatrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type origin(originSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type newstates(newstatesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cumuprobs(cumuprobsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type sMatrix(sMatrixSEXP);
    __result = Rcpp::wrap(stateT(origin, newstates, cumuprobs, sMatrix));
    return __result;
END_RCPP
}
