# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

stateT <- function(origin, newstates, cumuprobs, sMatrix) {
    .Call('ibmcraftr_stateT', PACKAGE = 'ibmcraftr', origin, newstates, cumuprobs, sMatrix)
}

